on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Make distribution
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14