name: UT Sanity Check on PRs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  run_uts:
    name: Run UTs
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        python-version: [2.7.18, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Test with pytest
      run: |
        pytest tests --durations=5 --durations-min=180.0 --timeout=120 -W ignore::DeprecationWarning